# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: MIT-0

plugins:
  - "@shopify/prettier-plugin-liquid"

semi: false

overrides:
  - files: "*.html"
    options:
      parser: liquid-html
