# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: MIT-0

# Site information
title: Samuel Wu
tagline: What is loving without knowing we are left to die
description: >-
  I'm Samuel, a Chinese-American student interested in technology, open source,
  and video games.
url: https://wushenrong.github.io/
repository: wushenrong/wushenrong.github.io

# Favicon
favicon:
  source: favicon.png

# Timezone and Locale
timezone: America/New_York
locale: en-US
lang: en-US

# Author information
author:
  name: Samuel Wu
  email: twopizza9621536@gmail.com
  url: https://wushenrong.github.io

minima:
  nav_pages:
    - pages/projects.html
    - pages/resume.html
    - pages/about.md
  show_excerpts: true
  social_links:
    - title: Samuel's GitHub Account
      icon: github
      url: https://github.com/wushenrong
    - title: Samuel at BlueSky
      icon: bluesky
      url: https://bsky.app/profile/wushenrong.github.io
    - title: Samuel at Mastodon
      icon: mastodon
      url: https://social.restless.systems/@TwoPizza9621536
    - title: Samuel at Tumblr
      icon: tumblr
      url: https://www.tumblr.com/blog/wushenrong
    - title: Samuel at Steam
      icon: steam
      url: https://steamcommunity.com/id/wushenrong/

# Page defaults and links
permalink: /:title/
collections_dir: collections

pagination:
  enabled: true
  per_page: 7
  sort_reverse: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: "pages"
    values:
      layout: page

  - scope:
      path: ""
    values:
      layout: default

# SASS/SCSS options
sass:
  style: compressed

# KaTeX support
jektex:
  ignore:
    - "*.xml"

# Strict mode
strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true

# Exclude files
exclude:
  - .ruby-lsp
  - LICENSE
  - LICENSES
  - package-lock.json
  - package.json
  - README.md
  - REUSE.toml

# Include files
include:
  - .well-known
