# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: MIT-0

version = 1

[[annotations]]
SPDX-FileCopyrightText = "2025 Samuel Wu"
SPDX-License-Identifier = "CC-BY-SA-4.0"
path = ["assets/favicon/**", "collections/**", "pages/**"]

[[annotations]]
SPDX-FileCopyrightText = "2013-2020 Khan Academy and other contributors"
SPDX-License-Identifier = "MIT"
path = ["assets/fonts/KaTeX_*"]

[[annotations]]
SPDX-FileCopyrightText = "2016-present Parker Moore and the minima contributors"
SPDX-License-Identifier = "MIT"
path = ["_includes/**", "_layouts/**", "pages/404.html"]

[[annotations]]
SPDX-FileCopyrightText = "2025 Samuel Wu"
SPDX-License-Identifier = "MIT-0"
path = [
  ".ruby-version",
  ".vscode/**",
  ".well-known/**",
  "assets/favicon/site.webmanifest",
  "Gemfile.lock",
  "package-lock.json",
  "package.json",
  "README.md",
]
