# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: MIT-0

- platform: github
  platform_name: GitHub
  user_url: https://github.com/wushenrong
- platform: bluesky
  platform_name: Bluesky
  user_url: https://bsky.app/profile/wushenrong.github.io
- platform: mastodon
  platform_name: Mastodon
  user_url: https://social.restless.systems/@TwoPizza9621536
- platform: tumblr
  platform_name: Tumblr
  user_url: https://www.tumblr.com/blog/wushenrong
- platform: steam
  platform_name: Steam
  user_url: https://steamcommunity.com/id/wushenrong/
